algoritmo "primo"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Receber um nº e informar se é primo
// Autor(a)    : Jeruso Alves Nascimento
// Data atual  : 18/08/2023
var

x: real

inicio
escreval("Digite um número: ")
leia(x)

se (( x / 1 = x) e (x / x = 1))entao 
escreval(x,"É um primo")
senao
escreval(x,"Não é primo")
fimse
fimalgoritmo