Algoritmo "ch1_1000"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/07/2023
Var
   // Seção de Declarações das variáveis
   i: inteiro
   

Inicio
   // Seção de Comandos, procedimento, funções, operadores,  etc...
    para i de 1 ate 100 passo 2 faca
       escreval(i)
    fimpara     
fimalgoritmo